#!/usr/bin/env python3
"""fetch_raw_wayback.py — retain the IRREPLACEABLE raw slice of the legislative corpus.

WHY ONLY 25 OF 305 (owner decision, 2026-07-29)
-----------------------------------------------
`legislative/` deliberately keeps markdown + text, not raw PDFs — the county's own PDFs
carry appended media packets (up to 47 MB each) and the whole live corpus is ~2.80 GB.
280 of the 305 `source_url`s still return HTTP 200, so those bytes are RE-FETCHABLE on
demand and their provenance pointers are already recorded in `minutes_index.csv`.

The other **25 documents are dead on the live site (every one HTTP 404)** and survive
only as Internet Archive captures — **129 MB, and the only irreplaceable bytes in the
module**.  Cache is also the repo's least-settled corpus (160 documents OCR'd on
2026-07-26; four extractor bugs found in that pass), so image-level re-verification
("did the OCR read this line right?") is a LIVE need here specifically — and that
question can only be answered from the original page image, not from the derived text.
Hence: retain these 25, fetch none of the other 280.

SOURCE OF TRUTH: `legislative/wayback_snapshots.csv` (25 rows, regenerated by
`recover_snapshots.py`), joined to `legislative/minutes_index.csv` on `snapshot_url` so
each retained PDF is named for the markdown document it backs.

BEHAVIOUR
  * serial, ~1.5 s between requests — web.archive.org is a donated public service
  * idempotent: an already-present, verified file is SKIPPED
  * every retained file is verified THREE ways — `%PDF` magic, a size floor, and a
    trailing `%%EOF` (truncation guard); a failure is RECORDED in `raw_index.csv` with
    its reason, never silently skipped (cardinal rule 1)
  * TRUNCATION FALLBACK (2026-07-29): the archive's first capture of 5 of these 25
    documents is cut off at exactly 1 MiB — a real, verifiable defect in that capture,
    not a transfer error (a re-request returns the same 1048576 bytes with no `%%EOF`).
    On a failed verification the script re-queries the CDX API for that live URL and
    tries the OTHER captures, largest record first, recording which capture won in
    `snapshot_used`.  If every capture is truncated that is written down as such —
    a truncated archive copy is still worth keeping and is marked `truncated`.
  * writes `legislative/raw_index.csv` — the retained-bytes ledger

    python3 fetch_raw_wayback.py [--force] [--sleep 1.5]
"""
import argparse
import csv
import hashlib
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPS = os.path.join(HERE, "wayback_snapshots.csv")
INDEX = os.path.join(HERE, "minutes_index.csv")
RAW = os.path.join(HERE, "raw")
LEDGER = os.path.join(HERE, "raw_index.csv")

UA = "civic-data-archive/1.0 (raw retention; +cache_county)"
MIN_BYTES = 10000          # a real minutes PDF is never this small; below = a soup/error page
CDX = ("https://web.archive.org/cdx/search/cdx?url=%s&output=json"
       "&filter=statuscode:200&filter=mimetype:application/pdf"
       "&fl=timestamp,original,mimetype,length")
COLS = ["date", "body", "provenance", "md_path", "raw_path", "snapshot_url",
        "snapshot_timestamp", "snapshot_used", "expected_bytes", "bytes", "sha256",
        "status", "note"]


def valid_pdf(path):
    """(ok, bytes, reason) — magic bytes, size floor, and an intact `%%EOF` trailer.

    The trailer test is what caught the archive's 1 MiB truncations: those files open
    with a perfectly good `%PDF-1.x` header and only END wrong."""
    try:
        n = os.path.getsize(path)
    except OSError as e:
        return False, 0, "stat failed: %s" % e
    with open(path, "rb") as f:
        head = f.read(5)
        f.seek(max(0, n - 2048))
        tail = f.read()
    if head[:4] != b"%PDF":
        return False, n, "not a PDF (leading bytes %r)" % head
    if n < MIN_BYTES:
        return False, n, "implausibly small (%d bytes < %d floor)" % (n, MIN_BYTES)
    if b"%%EOF" not in tail:
        return False, n, "TRUNCATED: no %%EOF trailer in the last 2 KB (%d bytes)" % n
    return True, n, ""


def cdx_captures(live_url):
    """All statuscode:200 application/pdf captures of `live_url`, largest record first."""
    q = CDX % urllib.parse.quote(live_url, safe="")
    for _ in range(3):
        try:
            req = urllib.request.Request(q, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.loads(resp.read().decode() or "[]")
            rows = data[1:] if len(data) > 1 else []
            rows.sort(key=lambda r: int(r[3]) if str(r[3]).isdigit() else 0, reverse=True)
            return [("https://web.archive.org/web/%sid_/%s"
                     % (r[0], urllib.parse.quote(r[1], safe=":/%?&=")), r[0]) for r in rows]
        except Exception:                                      # noqa: BLE001
            time.sleep(5)
    return []


def download(url, path):
    """(ok, reason) — fetch to `path`; never raises."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=300) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
        return True, ""
    except Exception as e:                                     # noqa: BLE001
        return False, "%s: %s" % (type(e).__name__, e)


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="re-fetch even if present+valid")
    ap.add_argument("--sleep", type=float, default=1.5, help="polite delay, seconds")
    args = ap.parse_args()

    with open(SNAPS, encoding="utf-8") as f:
        snaps = list(csv.DictReader(f))
    with open(INDEX, encoding="utf-8") as f:
        by_snap = {r["snapshot_url"]: r for r in csv.DictReader(f) if r.get("snapshot_url")}

    os.makedirs(RAW, exist_ok=True)
    out = []
    n_ok = n_skip = n_fail = 0
    for i, s in enumerate(snaps, 1):
        url = s["snapshot_url"]
        idx = by_snap.get(url)
        md = idx["md_path"] if idx else ""
        if not md:
            # never invent a filename: an unjoinable snapshot is recorded, not guessed
            out.append(dict(date=s["date"], body=s["body"], provenance=s["provenance"],
                            md_path="", raw_path="", snapshot_url=url,
                            snapshot_timestamp=s["snapshot_timestamp"],
                            expected_bytes=s.get("snapshot_bytes", ""), bytes="",
                            sha256="", status="unjoined",
                            note="snapshot_url not present in minutes_index.csv"))
            n_fail += 1
            continue
        name = os.path.basename(md)[:-3] + ".pdf"          # 2024-06-11_council.md -> .pdf
        path = os.path.join(RAW, name)
        rel = os.path.relpath(path, os.path.dirname(HERE))
        row = dict(date=s["date"], body=s["body"], provenance=s["provenance"],
                   md_path=md, raw_path=rel, snapshot_url=url,
                   snapshot_timestamp=s["snapshot_timestamp"], snapshot_used="",
                   expected_bytes=s.get("snapshot_bytes", ""), bytes="", sha256="",
                   status="", note="")

        if os.path.exists(path) and not args.force:
            ok, n, why = valid_pdf(path)
            if ok:
                row.update(bytes=n, sha256=sha256(path), status="present",
                           snapshot_used=url, note="already retained; not re-fetched")
                out.append(row)
                n_skip += 1
                print("[%2d/%d] SKIP  %-40s %10d B" % (i, len(snaps), name, n))
                continue
            print("[%2d/%d] REDO  %-40s (%s)" % (i, len(snaps), name, why))

        # try the ledger's chosen capture, then — only if it fails verification — the
        # archive's other captures of the same live URL, largest record first.
        tried, best, why = [], None, ""
        candidates = [(url, s["snapshot_timestamp"])]
        for cand, ts in candidates:
            got, err = download(cand, path)
            time.sleep(args.sleep)
            if not got:
                tried.append("%s (%s)" % (ts, err))
                why = err
            else:
                ok, n, why = valid_pdf(path)
                if ok:
                    best = (cand, ts, n)
                    break
                tried.append("%s (%s)" % (ts, why))
                if best is None or n > best[2]:
                    best = None                 # keep only a VERIFIED file as `best`
            if len(candidates) == 1:            # expand once, on the first failure
                alts = [c for c in cdx_captures(s["live_url"]) if c[0] != url]
                time.sleep(args.sleep)
                candidates.extend(alts)
                if alts:
                    print("        ... %d alternate capture(s) to try" % len(alts))

        if best:
            cand, ts, n = best
            row.update(bytes=n, sha256=sha256(path), status="fetched", snapshot_used=cand)
            if cand != url:
                row["note"] = ("ledger capture %s failed verification (%s); retained the "
                               "%s capture instead" % (s["snapshot_timestamp"],
                                                       tried[0].split("(", 1)[-1].rstrip(")"), ts))
            n_ok += 1
            print("[%2d/%d] OK    %-40s %10d B%s" % (i, len(snaps), name, n,
                                                     "  [alt capture %s]" % ts if cand != url else ""))
        else:
            # every capture failed. Keep whatever bytes we hold (a truncated archive copy
            # is still the only copy) and say so plainly.
            n = os.path.getsize(path) if os.path.exists(path) else 0
            row.update(bytes=n, sha256=sha256(path) if n else "",
                       status="truncated" if n else "fetch_failed",
                       snapshot_used=candidates[-1][0] if n else "",
                       note="NO complete capture in the Internet Archive — tried %d: %s. "
                            "The retained bytes are the archive's own partial record; the "
                            "extracted markdown remains the readable form."
                            % (len(tried), "; ".join(tried)))
            n_fail += 1
            print("[%2d/%d] PART  %-40s %10d B  (no complete capture; %d tried)"
                  % (i, len(snaps), name, n, len(tried)))
        out.append(row)

    with open(LEDGER, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLS)
        w.writeheader()
        w.writerows(out)

    good = [r for r in out if r["status"] in ("fetched", "present")]
    part = [r for r in out if r["status"] == "truncated"]
    total = sum(int(r["bytes"]) for r in out if str(r["bytes"]).isdigit())
    print("\n== retained %d/%d dead-URL documents complete, %d truncated-in-archive, "
          "%.1f MB on disk ==" % (len(good), len(snaps), len(part), total / 1e6))
    print("   verified-complete this run: %d ; already present: %d ; failed/partial: %d"
          % (n_ok, n_skip, n_fail))
    for r in part:
        print("   PARTIAL %s  %s" % (r["date"], os.path.basename(r["raw_path"])))
    print("   ledger: %s" % os.path.relpath(LEDGER, os.path.dirname(HERE)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
