#!/usr/bin/env python3
"""build_finance.py — Utah County campaign-finance STATED-TOTALS layer (module-local builder).

DERIVED. Regenerate with:  python3 utah_county/campaign_finance/build_finance.py

Inputs (curated, hand-verified — corrections go THERE, never into the CSVs):
    index.csv        one row per retained filing (regenerated by build_index.py)
    vision/*.json    one curated vision transcript per filing, keyed
                     sha1(index.csv `path`)[:8] — the repo-wide cf-vision cache convention

Outputs (SCHEMA.md §2/§3/§4 column contract, exactly):
    filing_totals.csv   one row per FILING (per REPORT for bundled PDFs)
    contributions.csv   the MACHINE-READABLE itemized layer (+ the trailing `geometry`, §2a)
    expenditures.csv    ditto

Why a module-local builder and not the shared engine's `driver.run()`: 245 of 263 filings are
tesseract OCR of HANDWRITTEN forms whose figures exist only as curated vision transcripts, and
`driver.run()` would rewrite all three CSVs from one parse pass. `utahcounty_schedab` IS now
registered in the shared registry (both printed variants), so this builder keeps the
vision-based stated totals and calls that family for the ITEMIZED layer of the **17
machine-readable filings** only (`index.format == 'text'`, i.e. `pdftotext -layout`, never an
OCR sidecar — CLAUDE.md: "Do not read text/*.txt as a transcript").

THE ITEMIZED LAYER (TRANCHE 3 Phase A, 2026-08-02)
  * `reconcile_cash_only=True` — the contribution anchor (Column A / Box B) is the CASH figure,
    and in-kind is a separate printed line, so the reconciliation sum counts cash rows only.
  * Every emitted side is RECONCILIATION-GATED against the stated total this module already
    publishes; a side that does not reconcile emits NOTHING plus a reason. No `stated_*` value
    is ever recomputed from an itemization.
  * THE COMPOUND `+Inkind` CELL. On the v.12.23 sheet Box B prints BOTH figures in one cell
    (`168872.24 +Inkind 7670.68`). This module's `money()` deliberately refuses to reduce that
    to one number, so `stated_total_contributions` is **BLANK** there — and stays blank. The
    family splits the cell on the form's own printed marker and reports the two parts
    separately, which is a DIVERGENCE from the published blank; the divergence is recorded in
    `notes`, the published total is not changed, and the family's itemized rows are published
    ALONGSIDE it with `reconciles_contrib` left blank (unknown) because there is no published
    figure to test against. What IS proven, and is stated in the note, is that the cash rows
    sum EXACTLY to the form's own printed cash component.
  * IN-KIND is asserted only where the family's per-page calibration reproduces the ledger's
    own printed IN-KIND total to the cent; otherwise the family reports every row as cash and
    flags it. That decision is the family's and is passed through untouched.

THE PROMOTION REGIME (documented, and the reason `filing_regime` says `per-period`):
both forms print a PER-PERIOD figure and a CUMULATIVE figure side by side.
    legacy_colAB  Column A "Total this Period"   | Column B "Year-to-Date Total"
    modern_boxAF  Box B / Box D  "this Period"   | Box C / Box E  "Year to Date"
`stated_total_contributions` / `stated_total_expenditures` carry the **PER-PERIOD** figure —
the increment. The cumulative figures are kept verbatim in `notes` (`ytd_contrib=` /
`ytd_expend=`) and in full in the vision transcript, and are **NEVER summed as increments**.
A cycle total is therefore Σ per-period rows, cross-checked against the LAST report's
cumulative — never a sum of the cumulative column.
"""
from __future__ import annotations

import csv
import decimal
import glob
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
D = lambda *p: os.path.join(HERE, *p)  # noqa: E731

CF_LIB = os.path.abspath(os.path.join(HERE, '..', '..', 'scripts', 'campaign_finance'))
sys.path[:0] = [CF_LIB, os.path.join(CF_LIB, 'families')]
import common            # noqa: E402
import normalize_donors  # noqa: E402
import reconcile         # noqa: E402
import registry          # noqa: E402

FAMILY_ID = 'utahcounty_schedab'

CONTRIB_HEADER = ['candidate', 'office', 'seat', 'election_year', 'filing_date',
                  'reporting_period', 'date', 'donor_raw', 'donor_normalized', 'donor_type',
                  'donor_city', 'donor_state', 'donor_district', 'amount', 'in_kind',
                  'is_incremental', 'source_filing', 'document_id', 'line_no',
                  'extraction_confidence', 'extract_method', 'needs_review']
EXPEND_HEADER = ['candidate', 'office', 'seat', 'election_year', 'filing_date',
                 'reporting_period', 'date', 'vendor_raw', 'vendor_normalized', 'purpose',
                 'amount', 'in_kind', 'is_incremental', 'source_filing', 'document_id',
                 'line_no', 'extraction_confidence', 'extract_method', 'needs_review']
TOTALS_HEADER = ['candidate', 'office', 'election_year', 'filing_date', 'reporting_period',
                 'filing_type', 'stated_total_contributions', 'stated_total_expenditures',
                 'stated_beginning_balance', 'stated_ending_balance', 'itemized_contrib_sum',
                 'itemized_expend_sum', 'reconciles_contrib', 'reconciles_expend',
                 'recon_delta_contrib', 'recon_delta_expend', 'self_funded_amount',
                 'n_contrib_rows', 'n_expend_rows', 'source_filing', 'document_id',
                 'extraction_confidence', 'notes', 'filing_regime']

CONF_ORDER = {'high': 3, 'medium': 2, 'low': 1, '': 0}
MONEY_RE = re.compile(r'^-?\$?\s*[\d,]*\.?\d+$')


def cache_key(path: str) -> str:
    """Repo-wide cf-vision cache convention: sha1(dataset-relative index path)[:8]."""
    return hashlib.sha1(path.encode()).hexdigest()[:8]


def money(raw):
    """(decimal_string, note).

    Three WHITELISTED, REVERSIBLE normalizations are applied — each one is a notation the
    filers of these forms actually use for a value they did print, and each is recorded in
    `notes` so the transform can be undone against the verbatim value in vision/<key>.json:

      1. written nil marks  `-0-` · `0.-` · the word `Zero`      -> `0`
      2. accountant's parentheses  `(65.00)`                      -> `-65.00`
      3. a dash in the CENTS position  `2,250.-`                  -> `2250.00`

    Everything else that is not a clean decimal stays **BLANK** with its verbatim form in the
    note — never repaired, never guessed. In particular a BARE dash (`-`) is NOT a zero (the
    filers who use it also write explicit zeros elsewhere on the same page), and a compound
    cell such as `94009.26 +Inkind 666.67` states two numbers and is not reduced to one.
    """
    s = (raw or '').strip()
    if s == '':
        return '', ''
    norm = ''
    t = s.replace('$', '').replace(',', '').strip()
    if t.lower() in ('-0-', '0.-', 'zero', '-0.-'):
        return '0', 'printed as %r (a written nil mark) — normalized to 0' % s
    neg = False
    if re.match(r'^\(.*\)$', t):
        t, neg = t[1:-1].strip(), True
        norm = 'printed in accountant\'s parentheses as %r — normalized to a negative' % s
    if re.match(r'^-?\d+\.-$', t):
        t = t[:-1] + '00'
        norm = ('printed with a dash in the cents position as %r — normalized to .00' % s
                if not norm else norm)
    if t in ('-', '.', ''):
        return '', 'unparseable printed value %r kept verbatim' % s
    if not MONEY_RE.match(t):
        return '', 'unparseable printed value %r kept verbatim' % s
    try:
        d = decimal.Decimal(t)
    except decimal.InvalidOperation:
        return '', 'unparseable printed value %r kept verbatim' % s
    if neg:
        d = -d
    return str(d), norm


def iso_date(raw):
    """Normalize the form's own Date of Report to ISO. Ambiguous/illegible -> blank."""
    s = (raw or '').strip()
    m = re.match(r'^(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})$', s)
    if not m:
        return ''
    mo, dy, yr = int(m.group(1)), int(m.group(2)), int(m.group(3))
    if yr < 100:
        yr += 2000
    if not (1 <= mo <= 12 and 1 <= dy <= 31 and 2005 <= yr <= 2030):
        return ''
    return '%04d-%02d-%02d' % (yr, mo, dy)


def weakest(conf_map, fields):
    seen = [conf_map.get(f, '') for f in fields if conf_map.get(f, '')]
    if not seen:
        return 'low'
    return min(seen, key=lambda c: CONF_ORDER.get(c, 0))


def load_index():
    with open(D('index.csv'), newline='') as fh:
        return list(csv.DictReader(fh))


def load_vision():
    out = {}
    for p in sorted(glob.glob(D('vision', '*.json'))):
        with open(p) as fh:
            try:
                j = json.load(fh)
            except json.JSONDecodeError as e:
                raise SystemExit('FAIL malformed vision cache %s: %s' % (p, e))
        k = os.path.basename(p)[:-5]
        if j.get('key') and j['key'] != k:
            raise SystemExit('FAIL vision cache %s declares key %r' % (p, j['key']))
        if j.get('path') and cache_key(j['path']) != k:
            raise SystemExit('FAIL vision cache %s: sha1(path)[:8] != filename (path=%r)'
                             % (p, j['path']))
        out[k] = j
    return out


# ---------------------------------------------------------------- the FIELD-SHIFT screen
# A form family reads a ledger by COLUMN GRAMMAR. Where a filing writes its dates in a shape
# the family's date regex does not know ("17 Jan 2026", "1.2.26", "5May26"), the date token
# lands in the NAME column and the real name slides into the next field — the amounts still
# sum to the printed total, so reconciliation alone cannot catch it. Two detectable shapes:
#   * a name field that IS a date token;
#   * a name/purpose field with no letters at all (an OCR artifact like "|" or "---").
# POLICY (uniform across this sweep, and the reason it is not one rule):
#   * >= 50% of a side's rows suspect  -> the family did not understand that section's column
#     grammar, so the WHOLE SIDE is WITHHELD with a reason (a systematically mis-columned
#     ledger is a wrong value, not a rough one);
#   * < 50%  -> an ISOLATED defect, almost always a filer's own malformed date on an otherwise
#     correctly parsed section; the rows are KEPT and flagged `needs_review=1`.
# Either way the finding is a FAMILY LIMITATION, documented not patched (the shared engine is
# frozen this phase) and queued for Phase B.
_DATEISH = re.compile(
    r"^\d{1,2}\s*[/.\-]{1,2}\s*\d{1,2}\s*[/.\-]{0,2}\s*\d{0,4}$"          # 5/20.14  1.2.26
    r"|^\d{1,2}\s*[A-Za-z]{3,9}\.?\s*,?\s*\d{2,4}$"                        # 17 Jan 2026  5May26
    r"|^[A-Za-z]{3,9}\.?\s*\d{1,2}\s*,?\s*\d{2,4}$")                       # Jan 17, 2026
_SHIFT_CUTOFF = 0.5


def _has_alpha(s):
    return any(ch.isalpha() for ch in s or "")


def screen_side(rows, name_field, side_label, notes, family_id):
    """Return the rows that may ship (possibly []). Appends every finding to `notes`."""
    if not rows:
        return rows
    suspect = []
    for x in rows:
        nm = (getattr(x, name_field, "") or "").strip()
        extra = (getattr(x, "purpose", "") or "").strip()
        why = None
        if _DATEISH.match(nm):
            why = "%s reads %r, a DATE token" % (name_field, nm)
        elif nm and not _has_alpha(nm):
            why = "%s reads %r, which carries no letters" % (name_field, nm)
        elif extra and not _has_alpha(extra):
            why = "purpose reads %r, which carries no letters" % extra
        if why:
            suspect.append((x, why))
    if not suspect:
        return rows
    frac = len(suspect) / len(rows)
    if frac >= _SHIFT_CUTOFF:
        notes.append(
            "ITEMIZED %s WITHHELD (FIELD SHIFT): %d of %d parsed row(s) are mis-columned — "
            "e.g. line %s: %s. The `%s` family did not recognise this filing's date format, so "
            "the date landed in the name column and the real name slid into the next field; "
            "the amounts still sum to the printed total, which is exactly why reconciliation "
            "cannot catch it. A systematically mis-columned ledger is a WRONG VALUE, so the "
            "whole side emits NOTHING. FAMILY LIMITATION, documented not patched — queued for "
            "Phase B."
            % (side_label, len(suspect), len(rows), suspect[0][0].line_no, suspect[0][1],
               family_id))
        return []
    for x, why in suspect:
        x.needs_review = "1"
    notes.append(
        "FIELD SHIFT (isolated, %d of %d rows KEPT and flagged needs_review=1): %s. The filer's "
        "own malformed date is not in the `%s` date grammar, so the token slid into the name "
        "column; the amount is unaffected and the side still reconciles. FAMILY LIMITATION, "
        "documented not patched."
        % (len(suspect), len(rows),
           "; ".join("line %s: %s" % (x.line_no, w) for x, w in suspect[:4]), family_id))
    return rows


def _fnum(v):
    try:
        return None if v in (None, '') else round(float(v), 2)
    except (TypeError, ValueError):
        return None


def itemize(r, mod_rows, aliases):
    """Parse ONE machine-readable filing and RECONCILIATION-GATE each side.

    `mod_rows` = this filing's already-built filing_totals rows (a bundled PDF has more than
    one). Returns (crows, erows, ft_patch, notes); the patch applies to the FIRST report only.
    """
    notes = []
    if r.get('format') != 'text':
        return [], [], {}, notes
    tp = D(r['text_path']) if r.get('text_path') else ''
    if not tp or not os.path.exists(tp):
        return [], [], {}, notes
    if len(mod_rows) > 1:
        notes.append('MULTI-REPORT PDF: %d reports are bundled in this file. The `%s` family '
                     'reads ONE face per parse, so reports 2..%d are GATED OUT — no itemized '
                     'row is published for them and nothing is merged into report 1. Flagged '
                     'for Phase B.' % (len(mod_rows), FAMILY_ID, len(mod_rows)))
        return [], [], {}, notes

    text = open(tp, encoding='utf-8', errors='replace').read()
    fam = registry.get(FAMILY_ID)
    m0 = mod_rows[0]
    meta = dict(candidate=m0['candidate'], office=m0['office'], seat='',
                election_year=m0['election_year'], filing_date=m0['filing_date'],
                reporting_period=m0['reporting_period'], source_filing=r['path'],
                document_id=m0['document_id'], extract_method=FAMILY_ID + '/text',
                is_scanned=False)
    res = fam.parse(text, meta)
    crows, erows = res['contrib_rows'], res['expend_rows']
    for x in crows:
        normalize_donors.normalize_contrib(x, meta['candidate'], aliases)
    for x in erows:
        normalize_donors.normalize_vendor(x)
    crows = screen_side(crows, 'donor_raw', 'contributions', notes, FAMILY_ID)
    erows = screen_side(erows, 'vendor_raw', 'expenditures', notes, FAMILY_ID)

    mod_c, mod_e = _fnum(m0['stated_total_contributions']), _fnum(m0['stated_total_expenditures'])
    fam_c, fam_e = _fnum(res.get('stated_contrib')), _fnum(res.get('stated_expend'))
    patch, keep = {}, {'contrib': list(crows), 'expend': list(erows)}

    for sidename, rows_, stated, famv, cash_only in (
            ('contrib', keep['contrib'], mod_c, fam_c, True),
            ('expend', keep['expend'], mod_e, fam_e, False)):
        if not rows_:
            continue
        ssum = round(sum(float(x.amount) for x in rows_
                         if x.amount and not (cash_only and x.in_kind == 'True')), 2)
        if stated is not None:
            rec, delta = reconcile.reconciles(ssum, stated)
            if rec is not True:
                notes.append('ITEMIZED %s WITHHELD: %d parsed row(s) sum to %.2f (%s) against '
                             'the published stated %.2f — the side does not reconcile, so '
                             'NOTHING is emitted (SCHEMA.md §6).'
                             % (sidename, len(rows_), ssum,
                                'cash rows only' if cash_only else 'all rows', stated))
                keep[sidename] = []
                continue
            patch['itemized_%s_sum' % sidename] = common.money_str(ssum)
            patch['reconciles_%s' % sidename] = 'True'
            patch['recon_delta_%s' % sidename] = '%.2f' % delta
        elif famv is not None and abs(ssum - famv) <= 0.01:
            # The published total is BLANK — on this form that means a COMPOUND `+Inkind` cell
            # this module deliberately refuses to reduce to one number. The rows are published
            # alongside the blank, never in place of it, and reconciliation stays UNKNOWN.
            patch['itemized_%s_sum' % sidename] = common.money_str(ssum)
            notes.append('COMPOUND-CELL DIVERGENCE (%s): this module publishes a BLANK stated '
                         'total because the form prints two numbers in one cell, and that blank '
                         'is UNCHANGED. The `%s` family splits the cell on the form\'s own '
                         'printed marker and reads %.2f; the itemized %s rows sum to %.2f, '
                         'EXACTLY that figure. Reconciliation stays blank (there is no published '
                         'figure to test against) and every row is flagged needs_review=1.'
                         % (sidename, FAMILY_ID, famv,
                            'cash' if cash_only else 'expenditure', ssum))
            for x in keep[sidename]:
                x.needs_review = '1'
        else:
            notes.append('ITEMIZED %s WITHHELD: the published stated total is blank and the '
                         '%d parsed row(s) (sum %.2f) match no printed figure on the face — '
                         'nothing is emitted.' % (sidename, len(rows_), ssum))
            keep[sidename] = []

    crows, erows = keep['contrib'], keep['expend']
    for x in crows + erows:
        x.extraction_confidence = 'high' if x.needs_review != '1' else 'low'
        x.needs_review = x.needs_review or '0'
    if crows or erows:
        patch['n_contrib_rows'] = len(crows)
        patch['n_expend_rows'] = len(erows)
        patch['self_funded_amount'] = common.money_str(round(sum(
            float(x.amount) for x in crows
            if x.donor_type in ('candidate-self', 'loan') and x.amount), 2))
        nik = sum(1 for x in crows if x.in_kind == 'True')
        patch['itemized_contrib_sum'] = patch.get('itemized_contrib_sum', '')
        notes.append('ITEMIZED LAYER: %d contribution (%d in-kind) / %d expenditure row(s) '
                     'parsed by the registered `%s` family from the machine-readable text '
                     'layer; the contribution anchor is CASH-ONLY (Column A / Box B); per-row '
                     '`geometry` records the amount cell read.'
                     % (len(crows), nik, len(erows), FAMILY_ID))
    if res.get('notes'):
        notes.append('family: ' + res['notes'])
    return crows, erows, patch, notes


def build(idx, vis):
    rows, missing, no_totals = [], [], []
    contrib_rows, expend_rows = [], []
    aliases = normalize_donors.load_aliases(D('donor_aliases.csv'))
    n_mr = 0
    for r in idx:
        path = r['path']
        k = cache_key(path)
        j = vis.get(k)
        if not j:
            missing.append(path)
            continue
        variant = j.get('form_variant', '')
        version = j.get('form_version', '')
        reports = j.get('reports') or []
        if not reports:
            no_totals.append(path)
        for i, rep in enumerate(reports, 1):
            t = rep.get('totals') or {}
            conf = rep.get('confidence') or {}
            notes_bits, valnotes = [], []

            c_now, n1 = money(t.get('contrib_this_period'))
            e_now, n2 = money(t.get('expend_this_period'))
            b_beg, n3 = money(t.get('balance_beginning'))
            b_end, n4 = money(t.get('balance_close'))
            c_cum, n5 = money(t.get('contrib_cumulative'))
            e_cum, n6 = money(t.get('expend_cumulative'))
            sub, n7 = money(t.get('subtotal_before_expend'))
            valnotes = [n for n in (n1, n2, n3, n4, n5, n6, n7) if n]

            notes_bits.append('variant=%s' % (variant or 'unknown'))
            if version:
                notes_bits.append('form=%s' % version)
            # CUMULATIVE figures live HERE, never in the stated_* increment columns.
            notes_bits.append('ytd_contrib=%s' % (c_cum or ''))
            notes_bits.append('ytd_expend=%s' % (e_cum or ''))
            if sub:
                notes_bits.append('subtotal_before_expend=%s' % sub)
            if rep.get('office_printed'):
                notes_bits.append('office_printed=%s' % rep['office_printed'])
            if rep.get('party_printed'):
                notes_bits.append('party_printed=%s' % rep['party_printed'])
            if rep.get('candidate_printed') and rep['candidate_printed'] != r['candidate']:
                notes_bits.append('candidate_index=%s (the channel label; this row carries the '
                                  'PAGE-FACE name)' % (r['candidate'] or '(blank)'))
            if rep.get('report_date'):
                notes_bits.append('report_date_printed=%s' % rep['report_date'])
            if rep.get('is_amendment'):
                notes_bits.append('amendment=%s' % rep['is_amendment'])
            if len(reports) > 1:
                notes_bits.append('report %d of %d bundled in this PDF' % (i, len(reports)))
            if rep.get('unreadable'):
                notes_bits.append('unreadable=%s' % ','.join(rep['unreadable']))
            if rep.get('scope_flag'):
                notes_bits.append('scope_flag=%s' % rep['scope_flag'])
            note_txt = '; '.join(notes_bits)
            tail = ' '.join(x for x in ([rep.get('notes') or ''] + valnotes) if x).strip()
            if tail:
                note_txt = note_txt + '. ' + tail

            # PORTAL LABELS LIE (GOTCHAS.md): the filer's own printed name on the form face is
            # the primary source; index.csv's `candidate` is the CHANNEL's label and is wrong
            # outright at least once (the county's 2020 Strapi record files Paul V. Child's
            # filing under Taylor Dayton). So the page face wins and the channel label is
            # preserved in `notes` whenever the two differ.
            cand = rep.get('candidate_printed') or r['candidate']
            doc_id = '%s|r%d' % (path, i)
            rows.append({
                'candidate': cand,
                'office': r['office'],
                'election_year': r['election_year'],
                'filing_date': iso_date(rep.get('report_date')),
                'reporting_period': r['reporting_period'],
                'filing_type': rep.get('report_type_printed', ''),
                'stated_total_contributions': c_now,
                'stated_total_expenditures': e_now,
                'stated_beginning_balance': b_beg,
                'stated_ending_balance': b_end,
                # This tranche transcribes cover + stated totals only. An EMPTY itemized layer
                # here means NOT TRANSCRIBED, not "no donors" — so the reconciliation columns
                # stay blank rather than reporting a fabricated mismatch (SCHEMA.md §6).
                'itemized_contrib_sum': '',
                'itemized_expend_sum': '',
                'reconciles_contrib': '',
                'reconciles_expend': '',
                'recon_delta_contrib': '',
                'recon_delta_expend': '',
                'self_funded_amount': '',
                'n_contrib_rows': 0,
                'n_expend_rows': 0,
                'source_filing': path,
                'document_id': doc_id,
                'extraction_confidence': weakest(conf, [
                    'contrib_this_period', 'expend_this_period',
                    'balance_beginning', 'balance_close']),
                'notes': note_txt,
                'filing_regime': 'per-period',
            })
    # ---- MACHINE-READABLE itemized layer (TRANCHE 3 Phase A). No-op on the 245 OCR'd
    # handwritten scans: itemize() returns immediately unless index.format == 'text'.
    by_src = {}
    for row in rows:
        by_src.setdefault(row['source_filing'], []).append(row)
    for r in idx:
        if r.get('format') != 'text':
            continue
        mod_rows = by_src.get(r['path'])
        if not mod_rows:
            continue
        n_mr += 1
        mod_rows.sort(key=lambda x: x['document_id'])
        _c, _e, patch, _n = itemize(r, mod_rows, aliases)
        contrib_rows.extend(_c)
        expend_rows.extend(_e)
        if _n:
            mod_rows[0]['notes'] = (mod_rows[0]['notes'] + '. ' if mod_rows[0]['notes']
                                    else '') + ' '.join(_n)
        mod_rows[0].update({k: v for k, v in patch.items() if v != ''})

    rows.sort(key=lambda x: (x['election_year'], x['office'], x['candidate'],
                             x['source_filing'], x['document_id']))
    contrib_rows.sort(key=lambda x: (x.source_filing, int(x.line_no or 0)))
    expend_rows.sort(key=lambda x: (x.source_filing, int(x.line_no or 0)))
    return rows, missing, no_totals, contrib_rows, expend_rows, n_mr


def write(path, header, rows):
    with open(path, 'w', newline='') as fh:
        w = csv.DictWriter(fh, fieldnames=header)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def write_rows(path, header, geo_header, rows):
    """Same trailing-optional-`geometry` contract as the shared driver (SCHEMA.md §2a)."""
    use = geo_header if any(getattr(x, common.GEOMETRY_COL, '') for x in rows) else header
    with open(path, 'w', newline='') as fh:
        w = csv.DictWriter(fh, fieldnames=use, extrasaction='ignore')
        w.writeheader()
        for x in rows:
            w.writerow(common.row_to_dict(x))


def main():
    idx = load_index()
    vis = load_vision()
    rows, missing, no_totals, crows, erows, n_mr = build(idx, vis)
    write(D('filing_totals.csv'), TOTALS_HEADER, rows)
    write_rows(D('contributions.csv'), CONTRIB_HEADER, common.CONTRIB_HEADER_GEO, crows)
    write_rows(D('expenditures.csv'), EXPEND_HEADER, common.EXPEND_HEADER_GEO, erows)

    # A cache whose filing has since been EXCLUDED from index.csv (a vision read proved it a
    # school-board filer) is not stale — it is the evidence for the exclusion, and the filing
    # is ledgered in out_of_scope.csv. Anything else with no index row IS stale and fails.
    ledgered = set()
    if os.path.exists(D('out_of_scope.csv')):
        with open(D('out_of_scope.csv'), newline='') as fh:
            notes = [r.get('note', '') for r in csv.DictReader(fh)]
        ledgered = {k for k in vis if any('vision/%s.json' % k in n for n in notes)}
    stale = sorted(set(vis) - {cache_key(r['path']) for r in idx} - ledgered)
    blank_c = sum(1 for r in rows if r['stated_total_contributions'] == '')
    blank_e = sum(1 for r in rows if r['stated_total_expenditures'] == '')
    print('index.csv          %3d filings' % len(idx))
    print('vision/            %3d transcripts (%d for filings ledgered out of scope)'
          % (len(vis), len(ledgered)))
    print('filing_totals.csv  %3d rows (%d bundled extra reports)'
          % (len(rows), len(rows) - len({r['source_filing'] for r in rows})))
    print('  blank stated contributions: %3d   blank stated expenditures: %3d'
          % (blank_c, blank_e))
    print('  confidence: %s' % {c: sum(1 for r in rows if r['extraction_confidence'] == c)
                                for c in ('high', 'medium', 'low')})
    nrc = sum(1 for r in rows if r['reconciles_contrib'] == 'True')
    nre = sum(1 for r in rows if r['reconciles_expend'] == 'True')
    print('machine-readable filings handed to `%s`: %3d of %d  (sides reconciling exactly: '
          '%d contrib / %d expend)' % (FAMILY_ID, n_mr, len(idx), nrc, nre))
    print('contributions.csv  %3d rows   expenditures.csv %3d rows  — the 245 handwritten '
          'scans itemize nothing (NOT transcribed, never "no donors")' % (len(crows), len(erows)))
    if missing:
        print('  %d filings WITHOUT a vision transcript (no filing_totals row):' % len(missing))
        for p in missing:
            print('    NO TRANSCRIPT', p)
    if no_totals:
        print('  %d transcripts with an empty reports[] (honest — nothing readable):'
              % len(no_totals))
        for p in no_totals:
            print('    EMPTY', p)
    if stale:
        print('  FAIL %d STALE vision cache(s) with no index.csv row:' % len(stale))
        for k in stale:
            print('    STALE vision/%s.json (%s)' % (k, vis[k].get('path', '?')))
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
